### ISSUE TITLE
Out of Class Work : Agile Terms

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#1]
[Here is a key list of Agile terms](https://github.com/IDX-597-05/Course-Information/wiki/C.-Agile-Terminologies) clustered into groupings. Please familiarize yourselves with these terms as we will be using them frequently in class. 

GitHub project management: a guide
https://www.zenhub.com/github-project-management
Review the difference between Agile Term and GitHub Term and ZenHub terms and relationships to GitHub

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

**Comment by akallish** [comment]
Hello @emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

Good Morning.

What is the status of this task?

- Remember any team member can move this task from "new issue" to "in progress" on the team kanban. 
- You also create a check box list if a team member has completed a task (besides having conversations about the task) like below:

- [ ] Jie An
- [x] Emery Donovan
- [ ] Lida Jiang 
- [ ] Yiwen Teng

You can also have conversations, add links, and add images to an issue to help complete a task.

**Comment by emerydonovan** [comment]
@akallish i'm trying to figure out how to indicate individual progress on each issue without closing it for the whole team, do you have suggestions? Thanks!

**Comment by akallish** [comment]
@emerydonovan good question.

I suggest creating a checklist with your team names that can be checked off by individuals. The product manager will be QA and then to closed.
