### ISSUE TITLE
Week 3 Out of Class Work : Create 20 user stories in Mural sandbox, port them to GitHub and put in backlog 

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#16]
Team 1 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698865902834/c3e08ec28643659c91b1dee3b7a5cbc00529db55?sender=u8174af0a23de37cd1e842670

- [x] Jie An 
- [x] Emery Donovan 
- [x] Lida Jiang 
- [x] Yiwen Teng

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

Team 2 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698865939019/19d50e89d272d706fd456e4a51e40067d4856ee0?sender=u8174af0a23de37cd1e842670

Team 3 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698865951278/0ca36d092656135ecdd50a1df87a22e0f54178b1?sender=u8174af0a23de37cd1e842670

- take all sub-hill statements and cluster them into groups
- name each group as this is your "epic" or body of work
- then write 20 user stories to address the details of your epics
- remember that while you have a main user, your team may have identified additional stakeholders that you need to write stories for

GitHub
- go into issues tab, and under tags, add epic tags
- open a new issue in GitHub
- give a story a name
- assign the team to the story
- give it a tag “story” and an "epic" tag
- choose week four milestone
- at the top of an issue, list the goal, the hill and which sub-hill the story is decomposed from
draft the iteration 0 of the hill statement
- choose five stories out of twenty, and team members iterate a few times to refine the story statement and then @ reference others on the team 

Just like the hills/definitions/sub hills exercise, it is important to refine the language of the story.
The product manager’s responsibility is to help refine draft story statements and weigh in on the final draft story statement. 

ZenHub
- move all stories into the backlog pipeline

**Comment by yiwenteng** [comment]
@akallish Hi Adam, about this one"go into issues tab, and under tags, add epic tags", "add epic tags", is it mean we create a new label? or should we use the exist one "stories and epics"?

**Comment by akallish** [comment]
@yiwenteng Thanks for the question. In mural your team massed sub hills into a shared theme. This becomes a body of work. Your team should create a functional name for the epic and create a tag with that name. Is that clear?

**Comment by akallish** [comment]
@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie Hello! Thanks @yiwentengfor posting six story drafts. Overall it is a great start. 

I reviewed and iterated on the story statements to show more specificity. Please extrapolate to the other story statements to iterate on. Since your epics have several features, highlight which feature the story is addressing. 

In GitHub modify your "Epic" tag and rename it "Epic # : (Name)." Also please choose the tag "Epics and Stories"

**Comment by akallish** [comment]
@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie make sure for every story that the goal, hill, and sub hill statement is listed.

**Comment by akallish** [comment]
@emerydonovan @lidajiang19 I visited your Hills sandbox additions today. Interesting workflow diagram. This is a nice logical decomposition!

First, your goal is a goal, but in our context is part of your chosen hill statement and is either a what or wow.

Your Hill statement should be a sub-hill statement as you are defining the tactics of how to engage with employees to register. 

Your focus is on non-email employees (which I find hard to believe as all employees should have emails!).  

You are focusing on the Poster as a vehicle to communicate.

Your last level are your stories. They really are about engaging employees who are in a building doing other things like placing them in hallways, workspaces and even cafeterias. The tactics are : awareness though financial savings, engagement with specific details that would resonate and the call to action is to : go to a registration event or to sign up online. All your story statements should focus on the "how" this happens through QR code, SMS, E-Mail, Registration events. The ultimate goal are actual sign ups.
