### ISSUE TITLE
Week 4 Out of Class Work : Watch Online Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#27]
Review these videos BEFORE branching and writing acceptance criteria

Story to Acceptance Criteria
[http://bit.ly/2E7JqGq](http://bit.ly/2E7JqGq)

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

**Comment by emerydonovan** [comment]
helpful to see acceptance criteria written out as a list, also useful to think about edge cases

**Comment by akallish** [comment]
@emerydonovan interesting comment. I guess acceptance criteria may highlight if the results are common or not. 

Usually edge cases refer to the probability or frequency of something happening.
