### ISSUE TITLE
Out of Class Work : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#8]
https://www.ibm.com/design/thinking/page/toolkit/activity/writing-hills

https://www.ibm.com/garage/method/practices/think/practice_hills/

- [x] Jie An
- [x] Emery Donovan
- [x] Lida Jiang 
- [x] Yiwen Teng

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

**Comment by akallish** [comment]
What stood out in terms of key points from these articles that resonated with you.

**Comment by emerydonovan** [comment]
It was interesting to read about why it's so critical that ALL terms (e.g. "quickly," "proactive" etc) must be defined to ensure everyone is crystal clear on what they mean. This makes the dictionary section of the Mural make more sense.

Also I liked this description of the function of hills being about the big picture: "Hills tell you where to go, but each team must figure out how to get there. Hills empower teams to make everyday decisions and be creative with their problem solving, while keeping sight of the big picture." It makes me think about mission and vision statements that organizations write... i wonder what are the similarities and differences there?

**Comment by akallish** [comment]
@emerydonovan Thank you for your thoughts. Yes, Hills supports an ultimate goal. So they are macro in nature. Mission and Vision statements (as originally defined by Tom Peters) which were all the rage ended up being liabilities because companies did not know how to bridge strategy into action. Hills, Sub-Hills are meant to decompose strategy into tactics.
