### ISSUE TITLE
Out of Class Work : Watch online videos 

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#9]
Former IBM General Manager of Design discussed IBM Design Thinking Foundation
https://www.youtube.com/watch?v=jU4fTt2DszE

- [x] Jie An
- [x] Emery Donovan
- [x] Lida Jiang 
- [x] Yiwen Teng

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

**Comment by akallish** [comment]
What stood out in terms of key points from Phil Gilbert that resonated with you.

**Comment by emerydonovan** [comment]
I liked the energetic, concise and engaging overview of the value of IBM design thinking workshops for non-designers. I also appreciated the clear overview of the structure of each workshop (independent work, group review, refinement, decision about feasibility) as well as what the purpose of these workshops is (refine, improve + innovate on an existing product, service or product; co-design a specific solution; scope and prioritize new projects and issues).

Obviously this workshop overview is for a very specific IBM context and I was left wondering about their decision making process to represent design thinking via its most generic symbols (sticky notes, group brainstorming) as opposed to the more rich, nuanced tools that design methodologies offer, such as ensuring that solutions are co-created with end users, end users being participants in the workshops, the power of physical prototyping to make ideas real, etc. I imagine that if I had watched this video a few years ago I might have assumed that design thinking was just getting a group of employees together in a room with sticky notes, which is a view that I think sometimes leads non-designers to dismiss the full value of design.

**Comment by akallish** [comment]
@emerydonovan thanks for your thoughtful response. Phil Gilbert is an incredible design leader. Using "the keys" of IBM design thinking empowers a structured design process with stakeholders (remember there are more than users) to explore and co create the future using specific methods to answer key questions.

IBM has open sourced IBM Design Thinking to many companies with great success.
